# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-18 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0008_auto_20180903_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Fname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
